### ISSUE TITLE
Feature: Add OnlyOffice as a subchart

### ISSUE THREAD

**Issue by jessebot** [nextcloud/helm#610]
## Description of the change

Let's add support for [OnlyOffice](https://www.onlyoffice.com/) as a subchart. Here's their [helm chart](https://github.com/ONLYOFFICE/Kubernetes-Docs).

- Split from #214

## Benefits

Allow users to have a document server deployed in this stack.

## Possible drawbacks

- Another thing to support.
- Unknown: Not sure how much we can facilitate actually configuring the connection between Nextcloud and OnlyOffice 🤷

Happy to discuss anything further!

## Tasks

These are the tasks that would need to be done for this issue to be considered complete:

- [ ] add tests in ci and/or helm unit-tests
- [ ] add OnlyOffice as a configurable sub-chart via parameters in values.yaml
- [ ] install the [OnlyOffice connector](https://apps.nextcloud.com/apps/onlyoffice) app

We can add more tasks if needed.
