### ISSUE TITLE
Feature: Add Collabora as a subchart

### ISSUE THREAD

**Issue by jessebot** [nextcloud/helm#611]
## Description of the change

Let's add support for [Collabora](https://www.collaboraonline.com/) as a subchart. Here's their [helm chart](https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm/collabora-online) and here's their [docs](https://sdk.collaboraonline.com/docs/installation/Kubernetes.html).

- Split from #214

## Benefits

Allow users to have a document server deployed in this stack.

## Possible drawbacks

- Another thing to support.
- Unknown: Not sure how much we can facilitate actually configuring the connection between Nextcloud and Collabora 🤷

Happy to discuss anything further!

## Tasks

These are the tasks that would need to be done for this issue to be considered complete:

- [ ] add tests in ci and/or helm unit-tests
- [ ] add Collabora as a configurable sub-chart via parameters in values.yaml
- [ ] install the app is there is one?

We can add more tasks if needed.
